core/urls.py
from django.urls import path

from core.views import ContactList, ContactCreate, ContactUpdate, ContactDelete

app_name = 'core'

urlpatterns = [
    path('', ContactList.as_view(), name='home'),
    path('contact_create/', ContactCreate.as_view(), name='contact_create'),
    path('contact_update/<int:pk>', ContactUpdate.as_view(), name='contact_update'),
    path('contact_delete/<int:pk>', ContactDelete.as_view(), name='contact_delete')
]

testovoe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from phone_field import PhoneField


class Contact(models.Model):
    last_name = models.CharField('Фамилия контакта', max_length=255, blank=True)
    first_name = models.CharField('Имя контакта', max_length=255, blank=True)
    surname = models.CharField('Отчество контакта', max_length=255, blank=True)
    organization = models.CharField('Организация', max_length=255, blank=True)
    job_telephone = PhoneField('Рабочий номер телефона', blank=True, unique=True)
    personal_telephone = PhoneField('Сотовый номер телефона', blank=True, unique=True)

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return f'{self.last_name}, {self.first_name}', {self.surname}

core/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core import models, filters


class ContactList(ListView):
    paginate_by = 5
    model = models.Contact
    template_name = 'homepage.html'
    context_object_name = 'contact'

    def get_filters(self):
        return filters.ContactFilter(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        context['count'] = self.get_queryset().count()
        return context


class ContactCreate(CreateView):
    model = models.Contact
    template_name = 'contact_create.html'
    context_object_name = 'contact_create'
    fields = '__all__'
    success_url = reverse_lazy('core:home')


class ContactUpdate(UpdateView):
    model = models.Contact
    template_name = 'contact_update.html'
    context_object_name = 'contact_update'
    fields = '__all__'
    success_url = reverse_lazy('core:home')


class ContactDelete(DeleteView):
    model = models.Contact
    template_name = 'contact_delete.html'
    context_object_name = 'contact_delete'
    success_url = reverse_lazy('core:home')
    title = "Удаление книги"

core/templates/contact_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить контакт</title>
</head>
<body>
    <form action="{% url 'core:contact_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

core/templates/contact_delete.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Удалить контакт</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить контакт?</p>
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger" value="Confirm">Удалить</button>
        <a class="btn btn-success" href="{% url 'core:home' %}" role="button">Отмена</a>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

core/templates/contact_update.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Обновить контакт</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Update">Изменить</button>
    </form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

core/templates/homepage.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Телефонный справочник</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <a href="{% url 'core:contact_create' %}">Добавить контакт</a>
    <h5> Кол-во контактов в справочнике: {{count}}</h5>
    <form method="GET">
        {{ filter.form.name.label }}<br>{{ filter.form.name }}
        <br>{{ filter.form.count.label }}<br>{{ filter.form.count }}
        <br><br><button type="submit">Поиск</button>
    </form>
    <br><h6>Примечание для поиска: оставьте 1 из 2 полей пустым, чтобы провести поиск по 1 полю. Заполните оба, чтобы поиск прошел по обоим полям.</h6>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Фамилия</th>
          <th scope="col">Имя</th>
          <th scope="col">Отчество</th>
          <th scope="col">Организация</th>
          <th scope="col">Рабочий телефон</th>
          <th scope="col">Личный телефон</th>
          <th scope="col">Редактировать</th>
          <th scope="col">Удалить</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for contact in contact %}
        <tr>
          <td>{{contact.id}}</td>
          <td>{{contact.last_name}}</td>
          <td>{{contact.first_name}}</td>
          <td>{{contact.surname}}</td>
          <td>{{contact.organization}}</td>
          <td>{{contact.job_telephone}}</td>
          <td>{{contact.personal_telephone}}</td>
          <td><a href="{% url 'core:contact_update' pk=contact.pk %}">Обновить</a></td>
          <td><a href="{% url 'core:contact_delete' pk=contact.pk %}">Удалить</a></td>
        </tr>
        {% empty %}
          <tr>
              <td> Список пуст </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <p><a href="?page=1">&laquo; Первая</a>
              <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a></p>
          {% endif %}
          <span class="current">
              <p> Страница {{page_obj.number}} из {{page_obj.paginator.num_pages}} </p>
          </span>
          {% if page_obj.has_next %}
              <p><a href="?page={{ page_obj.next_page_number }}">Следующая</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a></p>
          {% endif %}
      </span>
  </div>
  </body>
</html>